### PR TITLE
Added Stepped Line Style

### PR DESCRIPTION
**Pull request by kunalverma25**
Added support for Stepped Line Style for stepped style charts. #164

### CODE REVIEW

**Comment by willdale** [comment]
Before I do a full review, should the line draw horizontally from the first data point?
Screenshot 2022-01-16 at 09 51 04

rather than first vertically.

Simulator Screen Shot - iPhone 12 Pro - 2022-01-16 at 09 53 21

**Comment by kunalverma25** [comment]
Yup, horizontally.. Missed that somehow.. Updated..

**Comment by willdale** [comment]
It all looks good except for ranged line charts where the range box is off.

Stepped
ranged-stepped-issue

Line
reanged-line

**Comment by willdale** [comment]
- [ ] Fix ranged line chart

**Review by willdale — COMMENTED** [review]
- [ ] Fix ranged line chart

**Comment by kunalverma25** [comment]
Now range is working as expected..
Screenshot 2022-01-18 at 8 12 41 PM

**Review by willdale — APPROVED** [review]

**Pull request merged**
