### PR TITLE
Add podspec & x&y Axis border color options

### PR DESCRIPTION
**Pull request by bluesource**
I've added a simple podspec.

### CODE REVIEW

**Comment by bluesource** [comment]
I had the problem that the axis borders use a Divider. This color could not be changed. 
I added an option for y&x axis to handle that. I made it optional on purpose to minimize the risk of regressions.

Before:
Bildschirmfoto 2021-06-28 um 11 27 19

After:
Bildschirmfoto 2021-06-28 um 11 32 55

**Comment by willdale** [comment]
Hello, thanks for this. 

In `AxisBorders.swift`, the `yAxisBorderColour` is assigned to X axis border when it is set to its top position. Further down in the same file is `YAxisBorder` doesn't have the colour option attached.

Thanks,
Will

**Comment by willdale** [comment]
I can add a commit to the branch if that's easier.

**Comment by simonmoser-bluesource** [comment]
@willdale sorry for this!

Corrected in on the branch.

**Comment by willdale** [comment]
Thank you.

**Pull request merged**
